### ISSUE TITLE
Implement web UI with mako

### ISSUE THREAD

**Issue by kobayy3** [hwakabh/random-travelers#1]
ここらで作ってみてモチベあげる
* javascript
* ajax
* python

UI
* 金額上限入力
* 時間上限入力
* ガチャボタン
* スロットみたく結果出力
* 画面遷移なしでやりたい

**Comment by hwakabh** [comment]
@kobayy3 
Issue は細かく刻んだほうがよろしきです！
数コミットで Closed にできるくらいがちょうどよいかと！

**Comment by hwakabh** [comment]
@kobayy3 Assignee として指定してみました！

**Comment by kobayy3** [comment]
そなの？
ビシバシよろしゅう

2020年2月6日(木) 20:37 Hiroyuki Wakabayashi <notifications@github.com>:
